import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Footer from "@/components/Footer";
import Navigation from "@/components/Navigation";
import ThemeProvider from "@/components/ThemeProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    inter.className,
                    "mx-auto flex min-h-dvh max-w-screen-xl flex-col justify-between"
                )}
            >
                <ThemeProvider attribute="class" defaultTheme="dark">
                    <div className="contents">
                        <Navigation />
                        <main className="container my-6 flex flex-col gap-12 py-12">
                            {children}
                        </main>
                    </div>
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
