import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Footer from "@/components/Footer";
import Navigation from "@/components/Navigation";
import ThemeProvider from "@/components/ThemeProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn(inter.className, "container")}>
                <ThemeProvider attribute="class" defaultTheme="dark">
                    <Navigation />
                    <main className="my-6 flex flex-col gap-12 py-12">{children}</main>
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
