name: Lint code and compile setup script

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "**"

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [">=16.6.0 <17.x"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
              with:
                  fetch-depth: 2

            - name: Setup pnpm
              uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4
              with:
                  version: latest

            - name: Setup Node.js
              uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
              with:
                  node-version-file: .node-version
                  check-latest: true
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint code
              run: pnpm lint

    compile:
        needs: lint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [">=16.6.0 <17.x"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
              with:
                  fetch-depth: 2

            - name: Setup pnpm
              uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4
              with:
                  version: latest

            - name: Setup Node.js
              uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
              with:
                  node-version-file: .node-version
                  check-latest: true
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Compile test
              env:
                  NEXT_PUBLIC_NOTION_ACTIVE_USER: ${{ secrets.NEXT_PUBLIC_NOTION_ACTIVE_USER }}
                  NEXT_PUBLIC_NOTION_DATABASE_ID: ${{ secrets.NEXT_PUBLIC_NOTION_DATABASE_ID }}
                  NEXT_PUBLIC_NOTION_TOKEN: ${{ secrets.NEXT_PUBLIC_NOTION_TOKEN }}
              run: pnpm build && rm -rf .next
