name: Lint code and compile setup script

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "**"

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [">=16.6.0 <17.x"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
              with:
                  fetch-depth: 2

            - name: Setup pnpm
              uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
              with:
                  version: latest

            - name: Setup Node.js
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
              with:
                  node-version-file: .node-version
                  check-latest: true
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint code
              run: pnpm lint

    compile:
        needs: lint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [">=16.6.0 <17.x"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
              with:
                  fetch-depth: 2

            - name: Setup pnpm
              uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
              with:
                  version: latest

            - name: Setup Node.js
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
              with:
                  node-version-file: .node-version
                  check-latest: true
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Compile test
              env:
                  NEXT_PUBLIC_NOTION_ACTIVE_USER: ${{ secrets.NEXT_PUBLIC_NOTION_ACTIVE_USER }}
                  NEXT_PUBLIC_NOTION_DATABASE_ID: ${{ secrets.NEXT_PUBLIC_NOTION_DATABASE_ID }}
                  NEXT_PUBLIC_NOTION_TOKENV2: ${{ secrets.NEXT_PUBLIC_NOTION_TOKENV2 }}
              run: pnpm build && rm -rf .next
